apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g0td9qtc1-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/g0td9qtc1-dotnet-basic-gitops